### PR TITLE
Use spelling extension to spellcheck Sphinx docs

### PR DESCRIPTION
**Pull request by huonw**
This uses https://sphinxcontrib-spelling.readthedocs.io to spell check our rendered documentation. This includes:

- any text in `.rst` files in `docs`
- doc strings for functions/classes/modules
- text in notebooks

There's numerous examples of misspelled words, which this PR fixes. There are also many words that are correctly spelled but aren't recognised as correct (e.g. "GCN", names, and en-au spellings). This PR includes a whitelist of words in `docs/spelling_wordlist.txt` (the default path for the spelling extension), this whitelist includes the above, and can be expanded as necessary.

This is checked on CI, and includes an annotation containing the misspelled words, as well as guidance for how to add things to the whitelist. For example: https://buildkite.com/stellar/stellargraph-public/builds/4677 

image

(https://github.com/sphinx-contrib/spelling/pull/44 will make the display even more helpful by providing more context around a misspelled word).

See: #1368

### CODE REVIEW

**Comment by huonw** [comment]
Sorry about this one; it's a bit annoying to review. The sub-line highlighting seems to help, most of the updates were done automatically with `sed`, and I did a pass over the diff here myself & found & fixed a few incorrect changes (so hopefully there's fewer remaining).

**Comment by huonw** [comment]
Yeah, I considered that, but decided we'd end up including the en_US versions anyway. But maybe that's a better default given the origin of this project!

**Comment by kjun9** [comment]
> Yeah, I considered that, but decided we'd end up including the en_US versions anyway. 

Ah you mean we have both versions of spelling peppered throughout?

> But maybe that's a better default given the origin of this project!

Yeah up to you if you want to change it now, or just change it if it ever gets annoying to frequently run into spelling errors on CI from having aussie brains that produce aussie spelling by default

**Comment by huonw** [comment]
> Ah you mean we have both versions of spelling peppered throughout?

Yeah, there's a few. For instance, the "added" words in https://github.com/stellargraph/stellargraph/pull/1583/commits/4df82bcc28db30e259b94bf03351cce6ec050c36#diff-6ff8a5a167c079bdae3db3c19510f369

> Yeah up to you if you want to change it now, or just change it if it ever gets annoying to frequently run into spelling errors on CI from having aussie brains that produce aussie spelling by default

Changed it now 😄

**Pull request merged**
