### PR TITLE
Bugfix/1085_gcn_lstm_dogfooding

### PR DESCRIPTION
**Pull request by habiba-h**
Currently GCN-LSTM has two minor bugs:

- [x] - GCN-LSTM is broken to due using `layer_size` in some places vs using `layer_sizes` in other.

- [x] - GCN-LSTM breaks when multiple LSTM layers are passed

- [x] GCN-LSTM document univariate time series limitation #1350

GCN-LSTM demo has insufficient explanation for some aspects #1354

- [x]  The GCN-LSTM demo had a few places that were confusing in practice, e.g.:

	

- [x] •	the format of the sequence data (N x D, vs. D x N, and what the N and D mean)

	

- [x] •	labels on the plots

	

- [x] •	how and why the data was scaled

GCN-LSTM demo enhancements #1347

- [x] Dogfooding revealed some typos in the GCN-LSTM demo: "“Forcasting”, “#### References”, “paperr”, “Concretetly”, "perparation""

- [x] Also, the pre_len = 12 parameter might not correspond with 30mins as suggested in the demo.

Package relevant GCN-LSTM data preparation methods into StellarGraph #1345

- [x] Potentially pull some pre-rpocessing code into the demo notebook.

(duplicate)
GraphConvolutionLSTM construction fails due to inconsistent lstm_layer_size and lstm_layer_sizes #1341
(StellarGraph 1.0.0rc1 dogfooding.)

### CODE REVIEW

**Comment by habiba-h** [comment]
@kieranricardo  ready for review

**Comment by habiba-h** [comment]
> this is looking great @habiba-h! the demo downloaded the dataset and ran without a hitch, and the pre-processing code is nicely presented and explained 👍
> 
> Can you format the demo with `python ./scripts/format_notebooks.py --default --overwrite demos` to pass CI? And then I think its good to go 🎉

Thanks @kieranricardo  for the review. 
I did try `python ./scripts/format_notebooks.py --default --overwrite demo/demos/spatio-temporal/gcn-lstm-LA.ipynb`  
Just wanted to format my notebook and not inadvertently modify others. However, I got this error: 
```
Processing file demos/spatio-temporal/gcn-lstm-LA.ipynb
Formatter error: Cannot parse: 4:2:   %pip install -q stellargraph[demos]==1.0.0rc2
```

Should I comment the Google colab cell in the notebook?

**Comment by kieranricardo** [comment]
I'm not sure why that error happens, but it just means that the script didn't format that line and happens for all our demos. Your notebook will be fine to upload now that you've run the script :)

**Comment by huonw** [comment]
CI fails the Colab block is changed, because it has a strict format that is automatically inserted and enforced.

The error is because the `%pip ...` line isn't valid Python and so the black reformatting fails. It's harmless and ignored, although definitely a bit confusing.

It happens for every notebook, e.g. https://buildkite.com/stellar/stellargraph-public/builds/3622#7dcec74a-147c-414e-b36d-a460e32fdaa0/176-181

**Comment by huonw** [comment]
It looks like this was merged with the Buildkite CI failing, which shouldn't be done. If there's something confusing about a failure feel free to ask on the PR or Slack, rather than override it.

**Pull request merged**
