### PR TITLE
Revert "add github merged pr plugin"

### PR DESCRIPTION
**Pull request by youph**
Reverts stellargraph/stellargraph#276

### CODE REVIEW

**Comment by TheDen** [comment]
Given `pytest` in `requirements.txt` is set to `pytest>=3.6.0`, it's now pulling version `3.10.0` (released a few days ago)—[changelog](https://docs.pytest.org/en/latest/changelog.html)

There seems to be a regression, since the `-p no:cacheprovider` now fails, with the error 
```AttributeError: 'Config' object has no attribute 'cache'```

Removing the flag, the test run again (done locally), but we also get new `DeprecationWarnings`, e.g.,

```
/usr/local/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
```
and
```/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:923
  /usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:923: DeprecationWarning: builtin type EagerTensor has no __module__ attribute
```

We can either pin `pytest` to the previous version, or move forward with the latest release. What are your thoughts @youph @adocherty?

**Comment by adocherty** [comment]
I'm happy with either way – we don't need the latest features of `pytest` currently, so pinning may be the easiest solution right now.

**Comment by youph** [comment]
I guess pinning `pytest` to the previous version is better, since if we don't, the `-p no:cacheprovider` flag will fail depending on which version of `pytest` is installed, right?

**Comment by TheDen** [comment]
Yep, and you'll get all the extra warnings

**Comment by youph** [comment]
@TheDen I was just doing that, you beat me by 30 sec :)

**Pull request merged**
