### PR TITLE
Testing a simple string change to see if it passes tests

### PR DESCRIPTION
**Pull request by geoffj-d61**
Builds with even very minor changes seems to be repeatedly failing. Here is a deliberately minor change in a string - does it pass or does it break?

### CODE REVIEW

**Comment by youph** [comment]
The failing happens elsewhere, here's the log:
```
=================================== FAILURES ===================================
--
  | _________________ Test_GraphAttentionSparse.test_apply_concat __________________
  |  
  | self = <layer.test_graph_attention.Test_GraphAttentionSparse object at 0x7f92eeadf438>
  |  
  | def test_apply_concat(self):
  | gat = self.layer(
  | units=self.F_out,
  | attn_heads=self.attn_heads,
  | attn_heads_reduction="concat",
  | activation=self.activation,
  | kernel_initializer="ones",
  | )
  | x_inp, layer_inp = self.get_inputs()
  |  
  | # Instantiate layer with squeezed matrix
  | >       x_out = gat(layer_inp)
  |  
  | tests/layer/test_graph_attention.py:127:
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  | /usr/local/lib/python3.6/site-packages/keras/engine/base_layer.py:451: in __call__
  | output = self.call(inputs, **kwargs)
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  |  
  | self = <stellargraph.layer.graph_attention.GraphAttentionSparse object at 0x7f92ee939278>
  | inputs = [<tf.Tensor 'input_22:0' shape=(1, 10, 5) dtype=float32>, <tf.Tensor 'input_23:0' shape=(1, ?) dtype=int32>, <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f92eeb286d8>]
  | kwargs = {}, X = <tf.Tensor 'input_22:0' shape=(1, 10, 5) dtype=float32>
  | out_indices = <tf.Tensor 'input_23:0' shape=(1, ?) dtype=int32>
  | A_sparse = <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f92eeb286d8>
  |  
  | def call(self, inputs, **kwargs):
  | """
  | Creates the layer as a Keras graph
  |  
  | Notes:
  | This does not add self loops to the adjacency matrix.
  | The output indices are only used when `final_layer=True`
  |  
  | Args:
  | inputs (list): list of inputs with 4 items:
  | node features (size b x N x F),
  | output indices (size b x M),
  | sparse graph adjacency matrix (size N x N),
  | where N is the number of nodes in the graph,
  | F is the dimensionality of node features
  | M is the number of output nodes
  | """
  | X = inputs[0]  # Node features (1 x N x F)
  | out_indices = inputs[1]  # output indices (1 x K)
  | A_sparse = inputs[2]  # Adjacency matrix (1 x N x N)
  |  
  | >       if not isinstance(A_sparse, K.tf.SparseTensor):
  | E       AttributeError: module 'keras.backend' has no attribute 'tf'
  |  
  | stellargraph/layer/graph_attention.py:466: AttributeError
  | _________________ Test_GraphAttentionSparse.test_apply_average _________________
  |  
  | self = <layer.test_graph_attention.Test_GraphAttentionSparse object at 0x7f92eeb3fdd8>
  |  
  | def test_apply_average(self):
  | gat = self.layer(
  | units=self.F_out,
  | attn_heads=self.attn_heads,
  | attn_heads_reduction="average",
  | activation=self.activation,
  | kernel_initializer="ones",
  | attn_kernel_initializer="zeros",
  | bias_initializer="zeros",
  | final_layer=False,
  | )
  | x_inp, layer_inp = self.get_inputs()
  |  
  | # Instantiate layer with squeezed matrix
  | >       x_out = gat(layer_inp)
  |  
  | tests/layer/test_graph_attention.py:156:
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  | /usr/local/lib/python3.6/site-packages/keras/engine/base_layer.py:451: in __call__
  | output = self.call(inputs, **kwargs)
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  |  
  | self = <stellargraph.layer.graph_attention.GraphAttentionSparse object at 0x7f92eeb3f208>
  | inputs = [<tf.Tensor 'input_26:0' shape=(1, 10, 5) dtype=float32>, <tf.Tensor 'input_27:0' shape=(1, ?) dtype=int32>, <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f92ee945f28>]
  | kwargs = {}, X = <tf.Tensor 'input_26:0' shape=(1, 10, 5) dtype=float32>
  | out_indices = <tf.Tensor 'input_27:0' shape=(1, ?) dtype=int32>
  | A_sparse = <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f92ee945f28>
  |  
  | def call(self, inputs, **kwargs):
  | """
  | Creates the layer as a Keras graph
  |  
  | Notes:
  | This does not add self loops to the adjacency matrix.
  | The output indices are only used when `final_layer=True`
  |  
  | Args:
  | inputs (list): list of inputs with 4 items:
  | node features (size b x N x F),
  | output indices (size b x M),
  | sparse graph adjacency matrix (size N x N),
  | where N is the number of nodes in the graph,
  | F is the dimensionality of node features
  | M is the number of output nodes
  | """
  | X = inputs[0]  # Node features (1 x N x F)
  | out_indices = inputs[1]  # output indices (1 x K)
  | A_sparse = inputs[2]  # Adjacency matrix (1 x N x N)
  |  
  | >       if not isinstance(A_sparse, K.tf.SparseTensor):
  | E       AttributeError: module 'keras.backend' has no attribute 'tf'
  |  
  | stellargraph/layer/graph_attention.py:466: AttributeError
  | _________ Test_GraphAttentionSparse.test_apply_average_with_neighbours _________
  |  
  | self = <layer.test_graph_attention.Test_GraphAttentionSparse object at 0x7f92ee9d8438>
  |  
  | def test_apply_average_with_neighbours(self):
  | gat_saliency = self.layer(
  | units=self.F_out,
  | attn_heads=self.attn_heads,
  | attn_heads_reduction="average",
  | activation=self.activation,
  | kernel_initializer="ones",
  | attn_kernel_initializer="zeros",
  | bias_initializer="zeros",
  | final_layer=False,
  | saliency_map_support=True,
  | )
  |  
  | gat_origin = self.layer(
  | units=self.F_out,
  | attn_heads=self.attn_heads,
  | attn_heads_reduction="average",
  | activation=self.activation,
  | kernel_initializer="ones",
  | attn_kernel_initializer="zeros",
  | bias_initializer="zeros",
  | final_layer=False,
  | saliency_map_support=False,
  | )
  |  
  | x_inp, layer_inp = self.get_inputs()
  |  
  | # Instantiate layer with squeezed matrix
  | >       x_out_saliency = gat_saliency(layer_inp)
  |  
  | tests/layer/test_graph_attention.py:201:
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  | /usr/local/lib/python3.6/site-packages/keras/engine/base_layer.py:451: in __call__
  | output = self.call(inputs, **kwargs)
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  |  
  | self = <stellargraph.layer.graph_attention.GraphAttentionSparse object at 0x7f92ee9d8278>
  | inputs = [<tf.Tensor 'input_30:0' shape=(1, 10, 5) dtype=float32>, <tf.Tensor 'input_31:0' shape=(1, ?) dtype=int32>, <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f92ee9d8358>]
  | kwargs = {}, X = <tf.Tensor 'input_30:0' shape=(1, 10, 5) dtype=float32>
  | out_indices = <tf.Tensor 'input_31:0' shape=(1, ?) dtype=int32>
  | A_sparse = <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f92ee9d8358>
  |  
  | def call(self, inputs, **kwargs):
  | """
  | Creates the layer as a Keras graph
  |  
  | Notes:
  | This does not add self loops to the adjacency matrix.
  | The output indices are only used when `final_layer=True`
  |  
  | Args:
  | inputs (list): list of inputs with 4 items:
  | node features (size b x N x F),
  | output indices (size b x M),
  | sparse graph adjacency matrix (size N x N),
  | where N is the number of nodes in the graph,
  | F is the dimensionality of node features
  | M is the number of output nodes
  | """
  | X = inputs[0]  # Node features (1 x N x F)
  | out_indices = inputs[1]  # output indices (1 x K)
  | A_sparse = inputs[2]  # Adjacency matrix (1 x N x N)
  |  
  | >       if not isinstance(A_sparse, K.tf.SparseTensor):
  | E       AttributeError: module 'keras.backend' has no attribute 'tf'
  |  
  | stellargraph/layer/graph_attention.py:466: AttributeError
  | -------------------- generated xml file: /workdir/1514.xml ---------------------

```

**Comment by youph** [comment]
...and I can't reproduce these errors on my laptop. Weird!

**Comment by geoffj-d61** [comment]
I'm guessing someone changed the version of TensorFlow on the build kite server, maybe?

**Comment by youph** [comment]
> I'm guessing someone changed the version of TensorFlow on the build kite server, maybe?

I've pulled the updated requirements from develop, let's see if this fixes the errors.

**Comment by youph** [comment]
Now the build succeeds. Should we close this PR?

**Comment by geoffj-d61** [comment]
Fixed in develop.

**Pull request closed without merging**
