### PR TITLE
Run memory-heavy notebooks on CI, post-networkx removal

### PR DESCRIPTION
**Pull request by huonw**
In #809, we remove the networkx implementation of StellarGraph, which cuts the default memory use significantly. This allows a few more notebooks to run reliably on CI.

See: #819

### CODE REVIEW

**Comment by huonw** [comment]
Two of these notebooks still fail:

`node-link-importance-demo-gat.ipynb`: `nbclient.exceptions.DeadKernelError: Kernel died`

<details>

```
Executing Cell 60--------------------------------------
WARNING:tensorflow:Layer lambda_1 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.
 
If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.
 
To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.
 
Kernel died while waiting for execute reply.
Ending Cell 60-----------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nbclient/client.py", line 414, in _poll_for_reply
    msg = self.kc.shell_channel.get_msg(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/papermill/cli.py", line 235, in papermill
    execution_timeout=execution_timeout,
  File "/usr/local/lib/python3.6/site-packages/papermill/execute.py", line 104, in execute_notebook
    **engine_kwargs
  File "/usr/local/lib/python3.6/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/usr/local/lib/python3.6/site-packages/papermill/clientwrap.py", line 38, in execute
    self.papermill_execute_cells()
  File "/usr/local/lib/python3.6/site-packages/papermill/clientwrap.py", line 65, in papermill_execute_cells
    self.execute_cell(cell, index)
  File "/usr/local/lib/python3.6/site-packages/nbclient/client.py", line 563, in execute_cell
    exec_reply = self._poll_for_reply(parent_msg_id, cell, timeout)
  File "/usr/local/lib/python3.6/site-packages/nbclient/client.py", line 419, in _poll_for_reply
    self._check_alive()
  File "/usr/local/lib/python3.6/site-packages/nbclient/client.py", line 446, in _check_alive
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died
```

</details>

`stellargraph-metapath2vec.ipynb`: `nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 600 seconds.`

<details>

```
Executing Cell 7---------------------------------------
Timeout waiting for execute reply (600s).
Ending Cell 7------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/papermill/cli.py", line 235, in papermill
    execution_timeout=execution_timeout,
  File "/usr/local/lib/python3.6/site-packages/papermill/execute.py", line 104, in execute_notebook
    **engine_kwargs
  File "/usr/local/lib/python3.6/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/usr/local/lib/python3.6/site-packages/papermill/clientwrap.py", line 38, in execute
    self.papermill_execute_cells()
  File "/usr/local/lib/python3.6/site-packages/papermill/clientwrap.py", line 65, in papermill_execute_cells
    self.execute_cell(cell, index)
  File "/usr/local/lib/python3.6/site-packages/nbclient/client.py", line 556, in execute_cell
    self._handle_timeout(exec_timeout, cell)
  File "/usr/local/lib/python3.6/site-packages/nbclient/client.py", line 440, in _handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 600 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['from stellargraph.data import UniformRandomMetaPathWalk', 'from stellargraph import StellarGraph', '', '# Create the random walker', 'rw = UniformRandomMetaPathWalk(StellarGraph(g_nx))']
...
['    n=1,  # number of random walks per root node', '    metapaths=metapaths,  # the metapaths', ')', '', 'print("Number of random walks: {}".format(len(walks)))']
-------------------
```

</details>

**Comment by timpitman** [comment]
> Two of these notebooks still fail:
> 
> `node-link-importance-demo-gat.ipynb`: `nbclient.exceptions.DeadKernelError: Kernel died`
> 
> `stellargraph-metapath2vec.ipynb`: `nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 600 seconds.` (Related to #820/#860.)

I think I mistakenly added `stellargraph-metapath2vec.ipynb` to #819 - the problem is just speed, not memory.

**Comment by huonw** [comment]
Hm, unfortunately `node-link-importance-demo-gcn.ipynb` seems to be somewhat unreliable: it failed (https://buildkite.com/stellar/stellargraph-public/builds/1366#67dedcb6-570c-433b-a9f9-f79efb46a10a) and then a retry succeeded. I'm going to try running this build a few times to get a better sense of the reliability (sorry, agents).

**Comment by huonw** [comment]
It does seem to fail semi-regularly, in addition to the failure above
- https://buildkite.com/stellar/stellargraph-public/builds/1391#4783430d-04e2-4b77-9c23-a33b7fea249b
- https://buildkite.com/stellar/stellargraph-public/builds/1392#dfa1d236-9ffc-40bb-b0f6-7a3905724daa

**Comment by huonw** [comment]
This isn't ready, and we're likely to have to actually edit the code, so closing for now.

**Pull request closed without merging**
