### PR TITLE
use the snapshot black tag + fmt everything

### PR DESCRIPTION
**Pull request by TheDen**
PR:

* Updates the pipeline to use `stellargraph/black:snapshot` which is currently version `19.10b0`
* The image's entrypoint will fomat everything in the repo by default
* This PR formats the remaining python files so that CI passes
* The docker-plugin is also updates for the `black` step

### CODE REVIEW

**Comment by huonw** [comment]
Was there a reason that the `demos` folder wasn't being formatted with `black` before?

**Comment by TheDen** [comment]
Not sure, perhaps @youph can clarify? (I think they should)

**Comment by adocherty** [comment]
I think formatting the demos would be a good idea. There is also a script that formats the IPython notebooks in the demos folder as well in PR #523 .

**Comment by youph** [comment]
> Not sure, perhaps @youph can clarify? (I think they should)
I think it never occurred to us to do that, but does black recognise .ipynb files? (notebooks)

**Comment by TheDen** [comment]
Black does run again `ipynb` files, e.g.,

```$ black ./demos/node-classification/node2vec/stellargraph-node2vec-weighted-random-walks.ipynb
reformatted demos/node-classification/node2vec/stellargraph-node2vec-weighted-random-walks.ipynb
All done! ✨ 🍰 ✨  
```

**Comment by TheDen** [comment]
I was mistaken, when directory running `black` against `ipynb` files it does format them but renders them unreadable, which I assume it treats them as python code. However, on the CI It won't happen because running `black .` or `black demos` it only formats `.py` so the `ipynb` will be left alone

**Pull request merged**
