### PR TITLE
Feature/attri2vec link prediction

### PR DESCRIPTION
**Pull request by daokunzhang**
In this pull request, we aim to provide an attri2vec in-sample link prediction demo "demos/link-prediction/attri2vec-link-prediction.ipynb" . Though there already exists an attri2vec link prediction demo with the same name, it actually operates inductively to predict the links of out-of-sample demos. I change the name of the old version into "demos/link-prediction/attri2vec-out-of-sample-link-prediction.ipynb" and categories it into "inductive" column in the indexing documentation. In this way, our stellargraph library can be favoured with one additional inductive node representation learning algorithm in the "demos/README.md" file.

The "demos/link-prediction/attri2vec-link-prediction.ipynb" is built on "demos/link-prediction/node2vec-link-prediction.ipynb" with the same experimental setting. With node attributes incorporated into embedding learning, attri2vec is able to achieve better link prediction performance than node2vec under the same link prediction setting.

By the way, I also enhance the documentation of attri2vec demonstrations in the following aspects:

1. The introduction of attri2vec in "demos/embeddings/attri2vec-embeddings.ipynb", "demos/node-classification/attri2vec-node-classification.ipynb", and "demos/link-prediction/attri2vec-out-of-sample-link-prediction.ipynb" is a bit verbose. To make the demos more readable, I add an attri2vec illustration figure in "demos/embeddings/attri2vec-embeddings.ipynb", "demos/node-classification/attri2vec-node-classification.ipynb" use concise language to interpret the working mechanism of attri2vec, and I delete the detailed description in "demos/link-prediction/attri2vec-out-of-sample-link-prediction.ipynb" to make readers focus on how the links of out-of-sample nodes are predicted with the inductive node representation learning with attri2vec. 

2. As the attri2vec paper "Attributed Network Embedding via Subspace Discovery" has already been formally published by the journal of Data Mining and Knowledge Discovery, I replace the arXiv publisher with Data Mining and Knowledge Discovery in the attri2vec reference. This can make the attri2vec algorithm more convincing to readers and can also be taken as a research output of our stellargraph project.

I also make some minor changes on the node2vec wording introduction in the "demos/embeddings/keras-node2vec-embeddings.ipynb" and "demos/node-classification/keras-node2vec-node-classification.ipynb", as well as the word2vec illustration figure. I wish the description is more accurate and easier to be understood.

See: #1536

### CODE REVIEW

**Comment by huonw** [comment]
Hm, I'm a little confused by the purpose of this demo. In particular, it seems like this is strictly less general than the out-of-sample demo: 

- the old demo tests on out-of-sample nodes with out-of-sample edges
- the new demo tests on in-sample nodes with out-of-sample edges

Before I review in detail, could you explain a little bit more about the purpose of this demo compared to the old one? Is it designed to just be a comparison to the node2vec demo?

> I change the name of the old version into "demos/link-prediction/attri2vec-out-of-sample-link-prediction.ipynb" and categories it into "inductive" column in the indexing documentation. In this way, our stellargraph library can be favoured with one additional inductive node representation learning algorithm in the "demos/README.md" file

FWIW, given the functionality already exists (and the demo even shows it), it would be fine to have the inductive column just say "yes", we don't need to have a non-inductive demo as a contrast to be able to fill out the column.

> I also make some minor changes on the node2vec wording introduction in the "demos/embeddings/keras-node2vec-embeddings.ipynb" and "demos/node-classification/keras-node2vec-node-classification.ipynb", as well as the word2vec illustration figure. I wish the description is more accurate and easier to be understood.

Just a small point: it would be great to do this as a separate pull request. These sort of minor changes are good, and we can generally land them quickly. By combining them into this big pull request, they'll have to wait for all of the other changes to be approved before merging.

**Comment by daokunzhang** [comment]
Hi @huonw ,

Thanks for your feedback! The new added attri2vec link prediction demo indeed has some overlap with the original out-of-sample link prediction demo. However, they are operated in different settings. For the new added attri2vec link prediction demo, the node representations are learned transductively. We assume nodes are well connected in the training graph and we learn node representations and perform link prediction on the training graph. For the out-of-sample demo, the node representations are learned inductively, we assume the out-of-sample nodes are not available during the training time, and we learn a mapping function from node features to node representations on the in-sample training graph. To perform link prediction for the out-of-sample nodes, we infer the representation for out-of-sample nodes by applying the mapping function to the features of out-of-sample nodes.

Actually the former case (the new added link prediction demo) is more general case, with the links of all nodes are used to train node representations, and the latter case (out-of-sample demo) is a stricter case, as the links of out-of-sample nodes are not used to learn node representations. The purpose of the out-of-sample linked demo is mainly to evaluate the inductive learning performance of attri2vec, which can also be evaluated by other tasks, such as node classification.

> Just a small point: it would be great to do this as a separate pull request. These sort of minor changes are good, and we can generally land them quickly. By combining them into this big pull request, they'll have to wait for all of the other changes to be approved before merging.

Thanks for your great advice! I will wrap the minor changes on keras node2vec into a new bug fix pull request.

Best regards!
Daokun @daokunzhang

**Comment by huonw** [comment]
> Actually the former case (the new added link prediction demo) is more general case, with the links of all nodes are used to train node representations, and the latter case (out-of-sample demo) is a stricter case, as the links of out-of-sample nodes are not used to learn node representations. The purpose of the out-of-sample linked demo is mainly to evaluate the inductive learning performance of attri2vec, which can also be evaluated by other tasks, such as node classification.

I think we're approaching this from different directions: I'm saying that the _code_ for in-sample link prediction is less general than the code for out-of-sample link prediction. That is, someone who wants to do an in-sample task can start with an out-of-sample task and remove some functionality (holding out nodes).

The major purpose of our demos is to teach how to use an algorithm for some tasks, and secondarily it can be used for comparing algorithms. It seems like this demo is more focused at the latter?

**Comment by daokunzhang** [comment]
> I think we're approaching this from different directions: I'm saying that the _code_ for in-sample link prediction is less general than the code for out-of-sample link prediction. That is, someone who wants to do an in-sample task can start with an out-of-sample task and remove some functionality (holding out nodes).

I understand. However, the code for out-of-sample link prediction is not a direct generalisation of in-sample link prediction. Certainly, people can do in-sample link prediction by holding out nodes. However it will ignore the edges that already connect the hold-out nodes, which will incur imperfect performance. 

The difference between the out-of-sample and in-sample link prediction can be reflected in the dynamic vs. static aspect.  The out-of-samle link prediction works for the dynamic setting, where the out-of-sample nodes have not come yet when we learn node representations on the in-sample subgraph. However, the in-sample link prediction works on the static network, which is more general setting consistent with other link prediction demos. In this setting, some edges are removed from the original graph with the remaining training graph well connected.

**Comment by huonw** [comment]
> Certainly, people can do in-sample link prediction by holding out nodes. However it will ignore the edges that already connect the hold-out nodes in the training graph, which will incur imperfect performance.

I think that's still not quite what I mean: in-sample link prediction is effectively the same as out-of-sample link prediction, except 0 nodes are held out, plus some minor tweaks to how the edges are separated into train/test.

This is similar to how a static network is the same as a dynamic network, except without any changes (rephrased: a dynamic network is more general, because a static network is a special case when there's no new nodes/edges).

For this reason, dynamic networks and out-of-sample tasks are more general, because algorithms and code that work on dynamic networks or out-of-sample tasks will generally also work on static networks and in-sample tasks (with a few minor tasks).

**Comment by daokunzhang** [comment]
Hi @huonw ,

In this sense, I agree with you than the out-of-sample link prediction is more general than the in-sample link prediction. From this perspective, the purpose of this demo is mainly to evaluate the performance of attri2vec on in-sample link prediction task. Actually, it is a strong baseline of my ongoing research on link prediction. If you think it is not necessary, I can remove the in-sample attri2vec link prediction demo, and only preserve the part of document enhancement for attri2vec in this pull request. Do you think it is OK?

Daokun

**Comment by huonw** [comment]
I think it's ok. Another approach would be to have a single in-sample link prediction demo, where the data is prepared once, and then several algorithms are trained and tested. This might include Node2Vec, Attri2Vec, and any other similar algorithms. However, for now, I think it's fine to land this as is.

**Comment by daokunzhang** [comment]
Hi @huonw ,

This pull request has been rearranged by removing the attri2vec in-sample link prediction demo and only preserving the attri2vec documentation enhancement part.

Thanks,
Daokun

**Comment by daokunzhang** [comment]
Hi @timpitman ,

It will be interesting to compare the link prediction performance of different algorithms like, Node2Vec, Attri2Vec, GraphSage under the same edge split setting. I would like to have a try.

Daokun

**Pull request merged**
