### PR TITLE
Update to support TensorFlow 2 API

### PR DESCRIPTION
**Pull request by adocherty**
### Description

Update library to support Tensorflow2 API

Intial steps:

- [x] Run unit tests and update a list of tests that fail.
- [x] Investigate tests and summarize why they fail.
- [x] Implement simple fixes

### Reviewer checklist:

- [ ] all unit tests pass
- [ ] all demo note books pass
- [ ] functionality of `calibration.TemperatureCalibration._fit_temperature_scaling` is correct
- [ ] functionality of `GradientSaliencyGAT` is correct
- [ ] functionality of `GradientSaliency` is correct
- [ ] `test_misc.test_squeezedsparseconversion_axis` is correct
- [ ] `test_ensemble.py` is still valid with the tf graph cleanup code

### CODE REVIEW

**Comment by adocherty** [comment]
We need to merge develop into this branch to continue work.

**Comment by kieranricardo** [comment]
Reviewer checklist:

- [ ] all unit tests pass
- [ ] all demo note books pass
- [ ] functionality of `calibration.TemperatureCalibration._fit_temperature_scaling` is correct
- [ ] functionality of `GradientSaliencyGAT` is correct
- [ ] functionality of `GradientSaliency` is correct
- [ ] `test_misc.test_squeezedsparseconversion_axis` is correct
- [ ] `test_ensemble.py` is still valid with the tf graph cleanup code

**Comment by adocherty** [comment]
Thanks for the quick work @kieranricardo!  I've added your reviewer checklist to the initial comment to make it easier for reviewers.

**Comment by kieranricardo** [comment]
@youph 

- I've updates the CHANGELOG breaking change section
- I've merged #571 into this branch for visibility 
- Thats surprising! The buildkite builds are now quicker so I would've assumed we'd see a slight speed up if anything.

**Comment by kieranricardo** [comment]
I created issue #193 for disabling eager execution in the demos.

**Pull request merged**
