### PR TITLE
Add download links to demo notebooks on readthedocs (#1390)

### PR DESCRIPTION
**Pull request by timpitman**
Adding links to our html documentation to download the notebook source files - there's now a "Download this notebook" button at the top and bottom of each demo.

Our use of `.nblink` files for nbsphinx makes this a little more complicated than expected.

See: #1390

### CODE REVIEW

**Comment by timpitman** [comment]
> It's not obvious to me what part of the code is caused by nblink files? It looks like vaguely like what I would expect for having plain `ipynb`s directly in the `docs` directory?

The examples at https://nbsphinx.readthedocs.io/en/0.6.1/conf.py use a function `env.doc2path` to resolve document name to (somewhat relative) path, however that resolves to our .nblink paths.

**Comment by huonw** [comment]
As in, the paths stored the `nblink` files, pointing to the top-level `demos/` directory, rather than the paths to the `nblink` files?

Also, standard reminder that an issue number in a PR title isn't auto linked by GitHub. Without this, there's no public evidence of progress for someone without zenhub looking at the issue (https://github.com/stellargraph/stellargraph/issues/1390#ref-pullrequest-611574617, the "37 seconds ago" in the screenshot is from when I just edited the reference in):

image

**Comment by timpitman** [comment]
> As in, the paths stored the `nblink` files, pointing to the top-level `demos/` directory, rather than the paths to the `nblink` files?

it gives the path of the .nblink file; their examples assume that's the path of the .ipynb file.

**Comment by huonw** [comment]
I think that's what we want? The path of the nblink file is the eventual location of the ipynb file?

**Pull request merged**
