### PR TITLE
Enabled python 3.7 in setup.py also bumped up versions of libraries

### PR DESCRIPTION
**Pull request by adocherty**
Tensorflow can now be pip installed in Python 3.7 so we can now install stellargraph successfully in Python 3.7.  I've update the `setup.py` to make this work and increases the library versions of required software.

Please check that stellargraph in Python 3.7 works for you! In particular I haven't run all of the demos yet.

### CODE REVIEW

**Comment by youph** [comment]
I feel that we should wait till after the release with python 3.7 support.

**Comment by adocherty** [comment]
Avoided numpy warnings by rolling back numpy version. 

This warning is from scipy that are linked to gensim. This is difficult to avoid as it should be up to gensim to fix this:
```
/Users/doc019/.envs/sg37/lib/python3.7/site-packages/scipy/sparse/sparsetools.py:21: DeprecationWarning: `scipy.sparse.sparsetools` is deprecated!
scipy.sparse.sparsetools is a private module for scipy.sparse, and should not be used.
  _deprecated()
```

This warning occurs a lot and is related to Cython imports in scipy and scikit-learn. I have no idea why it is occuring:
```
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
```

There are many deprecation warnings coming from incompatibility between Tensorflow 1.13.1 and the latest version of Keras (2.2.4). We can't avoid these except by waiting for Keras to be updated. The Tensorflow warnings are:
```
WARNING:tensorflow:From /Users/doc019/.envs/sg37/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

WARNING:tensorflow:From /Users/doc019/.envs/sg37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

ARNING:tensorflow:From /Users/doc019/.envs/sg37/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

WARNING:tensorflow:From /Users/doc019/.envs/sg37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
```

For the Tensorflow warnings we have an option to move to tensorflow.keras, which while it reimplements the Keras API breaks stellargraph when a simple find/replace for Keras imports is done.

Many of these compatibility warnings will be difficult to deal with.  Therefore, I think we should not spend more time on this issue but rather move to supporting Tensorflow 2.0 and tensorflow.keras.

**Comment by adocherty** [comment]
Update: We should update the readme with a warning that Python 3.7 compatibility is experimental and there will be many deprecation warnings currently. I will ask for reviews again for Python 3.6 & 3.7 compatibility.

**Comment by adocherty** [comment]
More complications:

To reduce the deprecation warnings from numpy I fixed the numpy version to 1.14. While this works on both Python 3.6.* & 3.7.* on buildkite, it failed for Python 3.6 on my computer (macos) due to incompatibilities with tensorflow 1.13.1. 

Due to this I'm rolling back to higher versions of numpy and scipy.  We will get more deprecation warnings but at least stellargraph will still work in both 3.6 and 3.7.

**Comment by youph** [comment]
> Update: We should update the readme with a warning that Python 3.7 compatibility is experimental and there will be many deprecation warnings currently. I will ask for reviews again for Python 3.6 & 3.7 compatibility.

This is a good idea I think.

**Comment by adocherty** [comment]
I've added a brief warning on the warning messages when running with Python 3.7

**Comment by youph** [comment]
Please don't forget to updated CHANGELOG.md once this is finished and ready to merge.

**Pull request merged**
