### PR TITLE
Replace `.node\b` with `.nodes` for NetworkX 2.4

### PR DESCRIPTION
**Pull request by huonw**
This was done with textual search and replace:

    git grep --files-with-matches '\.node\b' | xargs sed -i '' 's/\.node\[/.nodes[/g'
    git grep --files-with-matches '\.node\b' | xargs sed -i '' 's/\.node(/.nodes(/g'
    git grep --files-with-matches '\.node\b' | xargs sed -i '' 's/\.node\./.nodes./g'

See: #503

### CODE REVIEW

**Comment by huonw** [comment]
I've merged this with `develop` which incorporates the hotfix #505, and thus made this PR also remove the version restriction on NetworkX.

**Comment by adocherty** [comment]
@youph @PantelisElinas This is a straighforward fix for the NetworkX 2.4+ compatibility issues (removal of the `graph.node` interface). 

@huonw hasn't assigned reviewers but I think this can be reviewed and merged nonetheless?

**Comment by youph** [comment]
@adocherty yes, let's review and merge. Does this change of method names affect the new abstract SG class?

**Comment by geoffj-d61** [comment]
@youph , anything to do with NetworkX is likely to affect my new design - it depends on whether this is code purely internal to the operation of the NetworkXStellarGraph implementation or not. I suspect that it is, because the new design abstracts away from relying on internals, meaning that merging shouldn't be too bad.

**Comment by adocherty** [comment]
In addition the function `nx.connected_component_subgraphs` is now deprecated and was being used in **./stellargraph-node2vec-weighted-random-walks.ipynb** – I've committed a change to fix this.

The original error was:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-bbe10817d187> in <module>
     15 # nodes and subgraphs; having these in the data does not prevent the
     16 # algorithm from running and producing valid results.
---> 17 g_nx_wt = max(nx.connected_component_subgraphs(g_nx_wt, copy=True), key=len)
     18 print("Largest subgraph statistics: {} nodes, {} edges".format(
     19     g_nx_wt.number_of_nodes(), g_nx_wt.number_of_edges()))

AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'
```

**Comment by youph** [comment]
Merge?

**Pull request merged**
