### PR TITLE
Check info() against literal expected output

### PR DESCRIPTION
**Pull request by huonw**
The `test_info_heterogeneous` test for `StellarGraph.info` on a heterogeneous graph was incorrect, because did not have some assertions when it should've.

This fixes that by checking the exact output for `info()`, meaning the full string including indentation/new lines. This is good because it means we're validating what the users see, and so will catch any mistakes that break the formatting.

### CODE REVIEW

**Comment by huonw** [comment]
(Sorry @kjun9 if you happened to be reviewing this right now, I had to do some merge fixing.)

**Review by kjun9 — APPROVED** [review]
Looks fine, but could we also just compare the strings directly, rather than using `in_sequence`? If we're adding more things to `info` we probably want to update the tests anyway right?

**Comment by huonw** [comment]
> Looks fine, but could we also just compare the strings directly, rather than using in_sequence? If we're adding more things to info we probably want to update the tests anyway right?

Do you mean type out the whole `info` string literally? I guess that's more reliable, in a sense.

**Comment by kjun9** [comment]
> Do you mean type out the whole info string literally?

Yes that's what I meant. It also looks simpler IMO

**Comment by huonw** [comment]
I'll switch to it.

**Comment by huonw** [comment]
I switched to it, and like it, because the output of this method is designed for humans, so it's much better to check exactly what it looks like 👍 

As a minor detail, the literal strings previously had trailing whitespace which isn't allowed by our CI (https://buildkite.com/stellar/stellargraph-public/builds/1979#annotation-whitespace), and so I had to make an edit to `info` itself to write `Edge types: none` instead of `Edge types: ` (with a trailing space) when a node type has no incident edges/edge types.

**Review by kjun9 — APPROVED** [review]

**Pull request merged**
