### PR TITLE
Bump version to 1.0.0

### PR DESCRIPTION
**Pull request by kjun9**
This bumps our version to 1.0.0 and updates the notebooks to use the correct version.

Once this is merged, I'll be opening a PR from the release branch into master for CI and final review purposes.

### CODE REVIEW

**Comment by kjun9** [comment]
Hmm that's annoying, the docs build timed out 😕 I'm gonna assume it's something like #1305 - anyone know how to restart the docs build by itself? otherwise I'll push an empty commit to restart CI altogether

**Comment by timpitman** [comment]
I'm a little worried we're pushing the limits of readthedocs now and may get timeouts regularly... eg https://github.com/readthedocs/readthedocs.org/issues/1767

**Comment by kjun9** [comment]
@timpitman there's some more context in this issue https://github.com/stellargraph/stellargraph/issues/1305

I think our builds aren't supposed to take near the 15 minutes allocated yet, and instead it seems more like a bug

... with that said, the docs build failed again https://readthedocs.org/projects/stellargraph/builds/10970162/, I think readthedocs is being particularly flaky today?

**Comment by huonw** [comment]
It looks like this failed again, for a different reason:

> There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (10970162).

**Pull request merged**
