### PR TITLE
Add docker timeout

### PR DESCRIPTION
**Pull request by kjun9**
see #1052

### CODE REVIEW

**Comment by kjun9** [comment]
Seeing the push hanging for a while at the end for a lot of the builds
https://buildkite.com/stellar/stellargraph-public/builds/2148
https://buildkite.com/stellar/stellargraph-public/builds/2149
https://buildkite.com/stellar/stellargraph-public/builds/2150
```
compose.buildkite-2148-override.yml push runner-3_6
--
  | Pushing runner-3_6 (index.docker.io/stellargraph/stellargraph-ci-runner:stellargraph-public-runner-3_6-build-2148)...
  | The push refers to repository [docker.io/stellargraph/stellargraph-ci-runner]
  | aa625b0843c3: Pushing [==================================================>]   1.98GB
  | aa9d835a52bd: Pushed
  | c85e33b022c1: Pushed
  | 0c273f833508: Pushed
  | 8ec6a04f59d6: Layer already exists
  | 4d42b373e1b2: Layer already exists
  | 352d42e186c2: Layer already exists
  | ba924bce9f5a: Layer already exists
  | 271910c4c150: Layer already exists
  | 6670e930ed33: Layer already exists
  | c7f27a4eb870: Layer already exists
  | e70dfb4c3a48: Layer already exists
  | 1c76bd0dc325: Layer already exists
```

**Comment by kjun9** [comment]
I tried a couple of things, but what worked for me was passing in the environment variables through the BK UI or the pre-command hook:

https://buildkite.com/stellar/stellargraph-public/builds?branch=bugfix%2F1052-docker-timeout

**Comment by kjun9** [comment]
@huonw 

> 12 minutes is quite a long timeout; did something smaller not work?

I tried 6 minutes and it didn't work: https://buildkite.com/stellar/stellargraph-public/builds/2145#0ee18aaf-0975-4745-a5a0-0eb13b3ddc5a

**Comment by huonw** [comment]
Hm, that's a pain. I wonder if we should consider a completely different approach like making the images smaller or something (but also merge this so that we're not having to constantly retry things on CI).

**Comment by kjun9** [comment]
Okay I've filed https://github.com/stellargraph/stellargraph/issues/1057 but I'll merge this for now

**Pull request merged**
