### PR TITLE
Have an explicitly cached docker image for running on CI

### PR DESCRIPTION
**Pull request by huonw**

### CODE REVIEW

**Comment by huonw** [comment]
This is using https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/244 while that's not landed yet. It seems that the `push` lines aren't working, so a new image isn't being pushed by each build step under the "permanent" tag, if it's being built.

**Comment by TheDen** [comment]
I think push isn't working due to the `run` script having an `exit` in the script https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/dd0a3f41f2f3d362e68bc9e0924bf718b8f6bff5/commands/run.sh#L308

**Comment by huonw** [comment]
Nice catch; I'm trying https://github.com/huonw/docker-compose-buildkite-plugin/commit/a18b2c39e0682cf806be8f121750047bc05f7e4e

**Comment by huonw** [comment]
This was closed accidentally, see: https://github.com/stellargraph/stellargraph/issues/786.

**Comment by huonw** [comment]
New PR: https://github.com/stellargraph/stellargraph/pull/788

**Pull request closed without merging**
