### PR TITLE
Release 1.0.0rc1

### PR DESCRIPTION
**Pull request by habiba-h**
PR for updating master with release 1.0.0rc1. See if all looks good?

### CODE REVIEW

**Comment by huonw** [comment]
> so I think what would be best is to go back to the state at latest develop and run the notebook script again

I think it's fine to just run that here, and add a new commit, and then just make sure to merge this with squash and merge into `release-1.0.0rc1`.

**Comment by habiba-h** [comment]
> so I think what would be best is to go back to the state at latest develop and run the notebook script again
> 
> I think it's fine to just run that here, and add a new commit, and then just make sure to merge this with squash and merge into `release-1.0.0rc1`.

I am not sure what I should commit and where?

**Comment by kjun9** [comment]
Do you also want to do 

> Update Changelog section header and "Full Changelog" link to point to specific version tag instead of HEAD.

in this PR? otherwise looks good 👍

**Comment by habiba-h** [comment]
@kjun9 this is what you are talking about? So this already seem to be fixed? Am I missing something?

```
Change Log

[1.0.0rc1](https://github.com/stellargraph/stellargraph/tree/v1.0.0rc1)

[Full Changelog](https://github.com/stellargraph/stellargraph/compare/v0.11.0...v1.0.0rc1)
```

**Comment by kjun9** [comment]
> @kjun9 this is what you are talking about? So this already seem to be fixed? Am I missing something?
> 
> ```
> Change Log
> 
> [1.0.0rc1](https://github.com/stellargraph/stellargraph/tree/v1.0.0rc1)
> 
> [Full Changelog](https://github.com/stellargraph/stellargraph/compare/v0.11.0...v1.0.0rc1)
> ```

Yep but as Huon pointed out, it's already been done as part of the changelog update https://github.com/stellargraph/stellargraph/pull/1287 so no need to do anything here 👍

**Pull request merged**
