### PR TITLE
Fixes for various minor demo issues

### PR DESCRIPTION
**Pull request by huonw**
- #1488 (Links to Cora dataset docs in loading-pandas don't work) `stellargraph.datasets.datasets` was switched to just `stellargraph.datasets` in #1157. https://stellargraph--1508.org.readthedocs.build/en/1508/demos/basics/loading-pandas.html#Real-data:-Homogeneous-graph-from-CSV-files
- #1489 (Neo4j still caps in notebook load-cora-into-neo4j.ipynb) replaced all instances of `Neo4J` with `Neo4j`, except for the ones in our class names, e.g. https://stellargraph--1508.org.readthedocs.build/en/1508/demos/connector/neo4j/directed-graphsage-on-cora-neo4j-example.html
- #1490 (Loading-pandas demo overlap doesn't have overlap) switched to the `overlap` dataframe. https://stellargraph--1508.org.readthedocs.build/en/1508/demos/basics/loading-pandas.html#Multiple-node-types
- #1491 (Bad link formatting in loading-saving-neo4j.ipynb) removed the extra `(` https://stellargraph--1508.org.readthedocs.build/en/1508/demos/basics/loading-saving-neo4j.html#Saving-predictions-into-Neo4j
- #1493 (Content from neo4j connector readme is lost) copied the content back in and converted to rST: https://stellargraph--1508.org.readthedocs.build/en/1508/demos/connector/neo4j/index.html
- #1494 (Heading not formatted properly in DGI demo) removed the extra indentation https://stellargraph--1508.org.readthedocs.build/en/1508/demos/embeddings/deep-graph-infomax-embeddings.html#Data-Generators
- #1501 (Attri2vec link prediction dataset description is formatted peculiarly) this switches to using a block quote `> ...` for the whole description, rather than leaving the code segments out of it https://stellargraph--1508.org.readthedocs.build/en/1508/demos/link-prediction/attri2vec-link-prediction.html#Loading-DBLP-network-data
- #1502 (Incorrect heading formatting in Node2Vec node classification demo) the `<a name="..."></a>` seemed to be confusing things, and it seemed like it didn't even work correctly in Jupyter Lab https://stellargraph--1508.org.readthedocs.build/en/1508/demos/node-classification/node2vec-node-classification.html#References

### CODE REVIEW

**Comment by kieranricardo** [comment]
woah read the docs is slower than buildkite!

**Comment by kjun9** [comment]
It was down for a little while - can you trigger another build?

**Comment by huonw** [comment]
Restarted 👍

**Comment by huonw** [comment]
It worked; I've added links to each relevant part to the PR description.

**Pull request merged**
